services:
  db:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: hamzaakram
      POSTGRES_PASSWORD: 123456789
      PGDATA: /var/lib/postgresql/data

    ports:
      - "5332:5432"
    networks:
      - db
    restart: unless-stopped
networks:
  db:
    driver: bridge